name: Deploy dev branch

on:
  push:
    branches:
      - dev

jobs:
  deploy_source:
    name: build and deploy lambda
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: ['3.1.x']
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet }}
        env:
          CI: true
      - name: default deploy
        uses: git_user/git_repo_name@v3
        with:
          stage: Dev
          aws_region: eu-west-1
          function_name: my-function
          zip_file: bundle.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
